# Generated by Django 6.0.3 on 2026-04-05 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_ai_analyses_used_user_is_pro_user_pro_since_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='resume',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
