# Generated by Django 6.0.3 on 2026-04-12 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_profile_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ats_analysed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='ats_analyses_used',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='ats_feedback',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='ats_score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
