# Generated by Django 6.0.3 on 2026-04-04 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='matching_skills',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='application',
            name='missing_skills',
            field=models.TextField(blank=True),
        ),
    ]
