# Generated by Django 6.0.3 on 2026-04-12 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_job_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('causal', 'Casual'), ('contract', 'Contract'), ('internship', 'Internship'), ('remote', 'Remote')], max_length=20),
        ),
    ]
